import { Images } from "../assets/Images/Images";

export const upcomingMatchesApiData = {
  message: "Upcoming matches fetched successfully",
  status: true,
  data: [
    {
      matchId: 100321,
      matchName: "England tour of India, 2025",
      matchDescription: "2nd ODI",
      matchFormat: "ODI",
      matchStartDate: "1739088000000",
      matchEndDate: "1739116800000",
      status: "Match starts at Feb 09, 08:00 GMT",
      team1: {
        teamId: 2,
        teamName: "India",
        teamSymbol: "IND",
        teamImage: "/matches/team-logos/IND.png",
      },
      team2: {
        teamId: 9,
        teamName: "England",
        teamSymbol: "ENG",
        teamImage: "/matches/team-logos/ENG.png",
      },
      venue: {
        ground: "Barabati Stadium",
        city: "Cuttack",
      },
    },
    {
      matchId: 100328,
      matchName: "England tour of India, 2025",
      matchDescription: "3rd ODI",
      matchFormat: "ODI",
      matchStartDate: "1739347200000",
      matchEndDate: "1739376000000",
      status: "Match starts at Feb 12, 08:00 GMT",
      team1: {
        teamId: 2,
        teamName: "India",
        teamSymbol: "IND",
        teamImage: "/matches/team-logos/IND.png",
      },
      team2: {
        teamId: 9,
        teamName: "England",
        teamSymbol: "ENG",
        teamImage: "/matches/team-logos/ENG.png",
      },
      venue: {
        ground: "Narendra Modi Stadium",
        city: "Ahmedabad",
      },
    },
    {
      matchId: 101065,
      matchName: "Pakistan ODI Tri-Series, 2025",
      matchDescription: "2nd ODI Match",
      matchFormat: "ODI",
      matchStartDate: "1739161800000",
      matchEndDate: "1739190600000",
      status: "Match starts at Feb 10, 04:30 GMT",
      team1: {
        teamId: 13,
        teamName: "New Zealand",
        teamSymbol: "NZ",
        teamImage: "/matches/team-logos/NZ.png",
      },
      team2: {
        teamId: 11,
        teamName: "South Africa",
        teamSymbol: "RSA",
        teamImage: "/matches/team-logos/RSA.png",
      },
      venue: {
        ground: "Gaddafi Stadium",
        city: "Lahore",
      },
    },
    {
      matchId: 101074,
      matchName: "Pakistan ODI Tri-Series, 2025",
      matchDescription: "3rd ODI Match",
      matchFormat: "ODI",
      matchStartDate: "1739350800000",
      matchEndDate: "1739379600000",
      status: "Match starts at Feb 12, 09:00 GMT",
      team1: {
        teamId: 3,
        teamName: "Pakistan",
        teamSymbol: "PAK",
        teamImage: "/matches/team-logos/PAK.png",
      },
      team2: {
        teamId: 11,
        teamName: "South Africa",
        teamSymbol: "RSA",
        teamImage: "/matches/team-logos/RSA.png",
      },
      venue: {
        ground: "National Stadium",
        city: "Karachi",
      },
    },
    {
      matchId: 101080,
      matchName: "Pakistan ODI Tri-Series, 2025",
      matchDescription: "Final",
      matchFormat: "ODI",
      matchStartDate: "1739523600000",
      matchEndDate: "1739552400000",
      status: "Match starts at Feb 14, 09:00 GMT",
      team1: {
        teamId: 106,
        teamName: "TBC",
        teamSymbol: "TBC",
        teamImage: "/matches/team-logos/TBC.png",
      },
      team2: {
        teamId: 106,
        teamName: "TBC",
        teamSymbol: "TBC",
        teamImage: "/matches/team-logos/TBC.png",
      },
      venue: {
        ground: "National Stadium",
        city: "Karachi",
      },
    },
    {
      matchId: 112479,
      matchName: "Ireland tour of Zimbabwe, 2025",
      matchDescription: "1st ODI",
      matchFormat: "ODI",
      matchStartDate: "1739518200000",
      matchEndDate: "1739547000000",
      status: "Match starts at Feb 14, 07:30 GMT",
      team1: {
        teamId: 12,
        teamName: "Zimbabwe",
        teamSymbol: "ZIM",
        teamImage: "/matches/team-logos/ZIM.png",
      },
      team2: {
        teamId: 27,
        teamName: "Ireland",
        teamSymbol: "IRE",
        teamImage: "/matches/team-logos/IRE.png",
      },
      venue: {
        ground: "Harare Sports Club",
        city: "Harare",
      },
    },
    {
      matchId: 109393,
      matchName: "Australia tour of Sri Lanka, 2025",
      matchDescription: "1st ODI",
      matchFormat: "ODI",
      matchStartDate: "1739332800000",
      matchEndDate: "1739361600000",
      status: "Match starts at Feb 12, 04:00 GMT",
      team1: {
        teamId: 5,
        teamName: "Sri Lanka",
        teamSymbol: "SL",
        teamImage: "/matches/team-logos/SL.png",
      },
      team2: {
        teamId: 4,
        teamName: "Australia",
        teamSymbol: "AUS",
        teamImage: "/matches/team-logos/AUS.png",
      },
      venue: {
        ground: "R.Premadasa Stadium",
        city: "Colombo",
      },
    },
    {
      matchId: 112677,
      matchName: "Australia tour of Sri Lanka, 2025",
      matchDescription: "2nd ODI",
      matchFormat: "ODI",
      matchStartDate: "1739505600000",
      matchEndDate: "1739534400000",
      status: "Match starts at Feb 14, 04:00 GMT",
      team1: {
        teamId: 5,
        teamName: "Sri Lanka",
        teamSymbol: "SL",
        teamImage: "/matches/team-logos/SL.png",
      },
      team2: {
        teamId: 4,
        teamName: "Australia",
        teamSymbol: "AUS",
        teamImage: "/matches/team-logos/AUS.png",
      },
      venue: {
        ground: "R.Premadasa Stadium",
        city: "Colombo",
      },
    },
    {
      matchId: 113721,
      matchName: "ICC Cricket World Cup League Two 2023-27",
      matchDescription: "50th Match",
      matchFormat: "ODI",
      matchStartDate: "1739167200000",
      matchEndDate: "1739196000000",
      status: "Match starts at Feb 10, 06:00 GMT",
      team1: {
        teamId: 304,
        teamName: "Oman",
        teamSymbol: "OMAN",
        teamImage: "/matches/team-logos/OMAN.png",
      },
      team2: {
        teamId: 161,
        teamName: "Namibia",
        teamSymbol: "NAM",
        teamImage: "/matches/team-logos/NAM.png",
      },
      venue: {
        ground: "Al Amerat Cricket Ground (Ministry Turf 1)",
        city: "Al Amerat",
      },
    },
    {
      matchId: 113730,
      matchName: "ICC Cricket World Cup League Two 2023-27",
      matchDescription: "51st Match",
      matchFormat: "ODI",
      matchStartDate: "1739340000000",
      matchEndDate: "1739368800000",
      status: "Match starts at Feb 12, 06:00 GMT",
      team1: {
        teamId: 304,
        teamName: "Oman",
        teamSymbol: "OMAN",
        teamImage: "/matches/team-logos/OMAN.png",
      },
      team2: {
        teamId: 15,
        teamName: "United States of America",
        teamSymbol: "USA",
        teamImage: "/matches/team-logos/USA.png",
      },
      venue: {
        ground: "Al Amerat Cricket Ground (Ministry Turf 1)",
        city: "Al Amerat",
      },
    },
    {
      matchId: 113733,
      matchName: "ICC Cricket World Cup League Two 2023-27",
      matchDescription: "52nd Match",
      matchFormat: "ODI",
      matchStartDate: "1739512800000",
      matchEndDate: "1739541600000",
      status: "Match starts at Feb 14, 06:00 GMT",
      team1: {
        teamId: 161,
        teamName: "Namibia",
        teamSymbol: "NAM",
        teamImage: "/matches/team-logos/NAM.png",
      },
      team2: {
        teamId: 15,
        teamName: "United States of America",
        teamSymbol: "USA",
        teamImage: "/matches/team-logos/USA.png",
      },
      venue: {
        ground: "Al Amerat Cricket Ground (Ministry Turf 1)",
        city: "Al Amerat",
      },
    },
  ],
};

export const sportsData = [
  { id: "0", name: "Cricket", icon: "cricket" },
  { id: "1", name: "Kabaddi", icon: "kabaddi" },
  { id: "2", name: "Football", icon: "football" },
  { id: "3", name: "BasketBall", icon: "football" },
  { id: "4", name: "Tennis", icon: "tennis" },
];

export const banners = [
  {
    image: Images.banner3,
  },
  {
    image: Images.banner3,
  },
  {
    image: Images.banner3,
  },
  {
    image: Images.banner3,
  },
];
