export const SET_LOGIN_DATA = 'SET_LOGIN_DATA';

export const SET_SELECTED_MATCH_DETAILS = 'SET_SELECTED_MATCH_DETAILS';
export const SET_SELECTED_PLAYER_LIST = 'SET_SELECTED_PLAYER_LIST';
export const SET_USER_DATA = 'SET_USER_DATA';
export const LOG_OUT = 'LOG_OUT';
